const string1 = document.getElementById('string-1')
console.log(string1.innerText)
const string2 = document.getElementById('string-2')
console.log(string2.innerText)
const string3 = document.getElementById('string-3')
console.log(string3.innerText)
const string4 = document.getElementById('string-4')
console.log(string4.innerText)
const string5 = document.getElementById('string-5')
console.log(string5.innerText)
const string6 = document.getElementById('string-6')
console.log(string6.innerText)